env:
  num_agent_per_scene: 40
  max_episode_steps: 256
  sensor_kwargs:
    - sensor_type: DEPTH
      uuid: depth
      resolution: [64, 64]
      position: [0, 0, 0.0]
      orientation: [0, 0, 0]
  scene_kwargs:
    path: "VisFly/datasets/visfly-beta/configs/scenes/box15_wall_box15_wall"
  dynamics_kwargs:
    dt: 0.02
    ctrl_dt: 0.02
    action_type: "bodyrate"
    ctrl_delay: true
    cfg: "drone_d435i"
  visual: true
  requires_grad: true
  tensor_output: true
  device: "cpu"
  r_type: 0  # Reward type parameter

# Evaluation environment
eval_env:
  num_agent_per_scene: 1
  max_episode_steps: 256
  visual: true
  tensor_output: true
  scene_kwargs:
    path: "VisFly/datasets/visfly-beta/configs/scenes/box15_wall_box15_wall"
    render_settings:
      mode: fix
      view: custom
      resolution: [1080, 1920]
      position: [[5.0, -8.0, 3.0], [5.0, 0.0, 1.0]]
      line_width: 6.0
      trajectory: true
  dynamics_kwargs:
    dt: 0.02
    ctrl_dt: 0.02
    action_type: "bodyrate"
    ctrl_delay: true
    cfg: "drone_d435i"
  requires_grad: false
  device: "cpu"
  r_type: 0
