env:
  num_agent_per_scene: 128
  num_scene: 1
  max_episode_steps: 256
  sensor_kwargs: []
  scene_kwargs:
    path: "VisFly/datasets/visfly-beta/configs/scenes/garage_empty"
  dynamics_kwargs:
    dt: 0.03
    ctrl_dt: 0.03
    action_type: "bodyrate"
    ctrl_delay: true
    cfg: "drone_d435i"
  visual: true
  requires_grad: true
  tensor_output: false
  device: "cpu"
  random_kwargs:
    state_generator:
      class: "Uniform"
      kwargs:
        - position:
            mean: [2.0, 0.0, 2.5]
            half: [1.0, 1.0, 0.5]
  target: [2.0, 0.0, 0.0]

# Evaluation environment configuration
eval_env:
  num_agent_per_scene: 1
  max_episode_steps: 256
  visual: true
  tensor_output: false
  scene_kwargs:
    path: "VisFly/datasets/visfly-beta/configs/scenes/garage_empty"
    render_settings:
      mode: fix
      view: custom
      resolution: [1080, 1920]
      position: [[2.0, -5.0, 3.0], [2.0, 0.0, 0.5]]
      line_width: 6.0
      trajectory: true
  dynamics_kwargs:
    dt: 0.03
    ctrl_dt: 0.03
    action_type: "bodyrate"
    ctrl_delay: true
    cfg: "drone_d435i"
  requires_grad: false
  device: "cpu"
  random_kwargs:
    state_generator:
      class: "Uniform"
      kwargs:
        - position:
            mean: [2.0, 0.0, 2.5]
            half: [1.0, 1.0, 0.5]
  target: [2.0, 0.0, 0.0]
